//
// Generated file, do not edit! Created by nedtool 5.6 from TlMsg.msg.
//

#ifndef __VEINS_TLMSG_M_H
#define __VEINS_TLMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
    #include "veins/base/utils/Coord.h"
    #include "veins/modules/messages/BaseFrame1609_4_m.h"
    #include "veins/base/utils/SimpleAddress.h"
// }}


namespace veins {

/**
 * Class generated from <tt>TlMsg.msg:28</tt> by nedtool.
 * <pre>
 * packet TlMsg extends BaseFrame1609_4
 * {
 *     Coord senderPos;
 *     Coord senderSpeed;
 *     string laneId;
 *     simtime_t timeStampP;
 *     LAddress::L2Type senderAddress = -1;
 * }
 * </pre>
 */
class TlMsg : public ::veins::BaseFrame1609_4
{
  protected:
    Coord senderPos;
    Coord senderSpeed;
    ::omnetpp::opp_string laneId;
    ::omnetpp::simtime_t timeStampP;
    LAddress::L2Type senderAddress;

  private:
    void copy(const TlMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TlMsg&);

  public:
    TlMsg(const char *name=nullptr, short kind=0);
    TlMsg(const TlMsg& other);
    virtual ~TlMsg();
    TlMsg& operator=(const TlMsg& other);
    virtual TlMsg *dup() const override {return new TlMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual Coord& getSenderPos();
    virtual const Coord& getSenderPos() const {return const_cast<TlMsg*>(this)->getSenderPos();}
    virtual void setSenderPos(const Coord& senderPos);
    virtual Coord& getSenderSpeed();
    virtual const Coord& getSenderSpeed() const {return const_cast<TlMsg*>(this)->getSenderSpeed();}
    virtual void setSenderSpeed(const Coord& senderSpeed);
    virtual const char * getLaneId() const;
    virtual void setLaneId(const char * laneId);
    virtual ::omnetpp::simtime_t getTimeStampP() const;
    virtual void setTimeStampP(::omnetpp::simtime_t timeStampP);
    virtual LAddress::L2Type& getSenderAddress();
    virtual const LAddress::L2Type& getSenderAddress() const {return const_cast<TlMsg*>(this)->getSenderAddress();}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TlMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TlMsg& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_TLMSG_M_H

